services:
  bot:
    build: .
    env_file: .env
    volumes:
      - ./data:/bot/data
      - ./config:/bot/config
    restart: "no"

  scheduler:
    image: mcuadros/ofelia:latest
    depends_on:
      - bot
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./ofelia.ini:/etc/ofelia/config.ini
